

export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS"
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL"
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST"

export const SEARCH_VIDEOS_SUCCESS = "SEARCH_VIDEOS_SUCCESS"
export const SEARCH_VIDEOS_FAIL = "SEARCH_VIDEOS_FAIL"
export const SEARCH_VIDEOS_REQUEST = "SEARCH_VIDEOS_REQUEST"